# Do not edit this file! It is generated automatically.
package ProgArm;
our %CODES = qw(Space 0 Backspace 14 Enter 28 Shift 2 Symbols 12 e 4 E 104 t 16 T 116 a 24 A 124 o 26 O 126 i 1 I 101 n 6 N 106 s 15 S 115 h 20 H 120 r 29 R 129 d 34 D 134 l 3 L 103 c 8 C 108 u 13 U 113 m 18 M 118 w 5 W 105 f 10 F 110 g 17 G 117 y 22 Y 122 p 25 P 125 b 27 B 127 v 30 V 130 k 32 K 132 j 7 J 107 x 21 X 121 q 35 Q 135 z 9 Z 109 Ctrl 19 Alt 11 Escape 23 Tab 31 );
our %KEYS = reverse %CODES;
