# Do not edit this file! It is generated automatically.
package ProgArm;
our %CODES = qw(Space 0 Backspace 14 Enter 28 Shift 2 Symbols 12 e 4 t 16 a 24 o 26 i 1 n 6 s 15 h 20 r 29 d 34 l 3 c 8 u 13 m 18 w 5 f 10 g 17 y 22 p 25 b 27 v 30 k 32 j 7 x 21 q 35 z 9 Ctrl 19 Alt 11 Escape 23 Tab 31 );
our %KEYS = reverse %CODES;
